#pragma once

#include <math.h>
#include <cgv/range/expression/unary_expression.h>
#include <cgv/range/expression/binary_expression.h>

namespace cgv {
	namespace range {
		CGV_RANGE_EXPRESSION_UNARY_FUNCTION(sqrt)
		CGV_RANGE_EXPRESSION_UNARY_FUNCTION(exp)
		CGV_RANGE_EXPRESSION_UNARY_FUNCTION(log)
		CGV_RANGE_EXPRESSION_UNARY_FUNCTION(log10)
		CGV_RANGE_EXPRESSION_UNARY_FUNCTION(fabs)
		CGV_RANGE_EXPRESSION_UNARY_FUNCTION(sin)
		CGV_RANGE_EXPRESSION_UNARY_FUNCTION(cos)
		CGV_RANGE_EXPRESSION_UNARY_FUNCTION(tan)
		CGV_RANGE_EXPRESSION_UNARY_FUNCTION(ceil)
		CGV_RANGE_EXPRESSION_UNARY_FUNCTION(floor)
		CGV_RANGE_EXPRESSION_BINARY_FUNCTION(pow)
	}
}
